"""Type stubs for PyTerrainMap Python bindings."""

from typing import Dict, List, Optional, Tuple

__version__: str

Persona: Dict[str, str]

class PyGeoPoint:
    """Geographic point (latitude, longitude)."""
    lat: float
    lon: float

    def __init__(self, lat: float, lon: float) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: PyGeoPoint) -> bool: ...
    def distance_m(self, other: PyGeoPoint) -> float: ...

class PyRegion:
    """Geographic region (bounding box)."""
    north: float
    south: float
    east: float
    west: float

    def __init__(self, north: float, south: float, east: float, west: float) -> None: ...
    def __repr__(self) -> str: ...
    def contains(self, point: PyGeoPoint) -> bool: ...
    def center(self) -> PyGeoPoint: ...
    @staticmethod
    def world() -> PyRegion: ...

class PyObservation:
    """Single sensor observation."""
    robot_id: str
    timestamp: int
    sensor_type: str
    confidence: float

    def __init__(
        self,
        robot_id: str,
        timestamp: int,
        lat: float,
        lon: float,
        sensor_type: str,
        value_json: str,
        confidence: float,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def location(self) -> PyGeoPoint: ...
    def value(self) -> str: ...

class PyQueryResult:
    """Results from spatial-temporal query."""
    def __repr__(self) -> str: ...
    def observations(self) -> List[PyObservation]: ...
    def statistics(self) -> Dict[str, object]: ...

class PyTerrainMap:
    """Main terrain mapping engine."""
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def add_observation(self, obs: PyObservation) -> None: ...
    def query_region(self, region: PyRegion) -> PyQueryResult: ...
    def statistics(self) -> Dict[str, object]: ...
    def observations(self) -> List[PyObservation]: ...
    def clear(self) -> None: ...

class PyTerrainAnalysis:
    """Terrain intelligence analysis for a location."""
    location: Tuple[float, float]
    summary: str
    observations: List[str]
    risks: List[PyRisk]
    confidence: float

    def __init__(self, lat: float, lon: float) -> None: ...
    def __repr__(self) -> str: ...
    def advice_for(self, persona: str) -> List[str]: ...
    def add_observation(self, obs: str) -> None: ...
    def add_risk(self, risk: PyRisk) -> None: ...
    def add_recommendation(self, persona: str, recommendation: str) -> None: ...

class PyRisk:
    """Risk assessment for terrain analysis."""
    risk_type: str
    severity: float
    description: str
    affected_personas: List[str]
    mitigations: List[str]

    def __init__(self, risk_type: str, severity: float, description: str) -> None: ...
    def __repr__(self) -> str: ...
    def severity_label(self) -> str: ...
    def affects(self, persona: str) -> PyRisk: ...
    def with_mitigation(self, mitigation: str) -> PyRisk: ...

class PyMobilityAssessment:
    """Robot mobility assessment for terrain."""
    traversable: bool
    difficulty: float
    hazards: List[str]
    recommended_speed_ms: float
    battery_impact: float
    time_to_cross_100m_seconds: float

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def difficulty_label(self) -> str: ...
    def add_hazard(self, hazard: str) -> None: ...

class PyEnvironmentalConditions:
    """Environmental conditions (weather + soil)."""
    location: Tuple[float, float]
    mission_suitability: float

    def __init__(self, lat: float, lon: float) -> None: ...
    def __repr__(self) -> str: ...
    def update_suitability(self, score: float) -> None: ...

class PyDataExplanation:
    """Explanation of a data field for agent introspection."""
    field: str
    description: str
    applications: List[str]
    confidence: float
    source: str
    units: str
    normal_range: str

    def __init__(
        self,
        field: str,
        description: str,
        confidence: float,
        source: str,
        units: str,
        normal_range: str,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def add_application(self, app: str) -> None: ...

    @staticmethod
    def soil_moisture() -> PyDataExplanation: ...

    @staticmethod
    def temperature() -> PyDataExplanation: ...

    @staticmethod
    def visibility() -> PyDataExplanation: ...

    @staticmethod
    def slope() -> PyDataExplanation: ...
